# Tell Starship to use the custom matugen palette defined at the bottom of the file
palette = "colors"

format = """
 $username\
[@](fg:color7)\
$os \
[❯](fg:color7) \
  $directory [❯](fg:color7) \
$python\
$git_branch\
$git_status\
$fill\
$status\
$cmd_duration\
[❮](fg:color7)\
$time\
[ ](fg:color7)
 $character"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "fg:color8"
style_root = "fg:color9"
format = '[$user]($style)'
disabled = false

[status]
style = ''
symbol = '[✘ ](fg:color9)'
success_symbol = '[✔ ](fg:color8)'
format = '[[$signal_name ](fg:color9)$symbol]($style)'
map_symbol = false
disabled = false

[character]
success_symbol = '[❯](fg:color9 bold)'
error_symbol = '[❯](fg:color9)'
vicmd_symbol = '[❯](fg:color1)'
disabled = false

[cmd_duration]
min_time = 1
style = 'fg:color1'
format = '[[$duration](bold fg:color8)  ]($style)'

[hostname]
ssh_only = false
style = 'fg:color3'
format = '[@$hostname ]($style)'
disabled = false

[os]
style = "fg:color1"
format = "[$symbol]($style)"
disabled = false

[directory]
style = "fg:color1"
format = "[$path]($style)"
truncation_length = 9
truncation_symbol = "…/"
truncate_to_repo = false
home_symbol = "~"
use_os_path_sep = true

[directory.substitutions]
#"~/" = "~./"
"~" = " "

[fill]
symbol = ' '

[c]
symbol = ""
style = ""
format = '[ $symbol ]($style)'

[docker_context]
symbol = " "
style = ""
format = '[ $symbol $context ]($style) $path'

[git_branch]
style = "fg:color10"
format = '(fg:color10)[ ](fg:color10)[ $branch ](bold $style)'

[git_status]
style = "fg:color8"
conflicted = "~"
up_to_date = " "
untracked = "?"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "*"
modified = " "
staged = '[++\($count\)](fg:color8)'
renamed = " "
deleted = " "
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "go"
style = "fg:#FFFFFF" 
format = '[ $symbol ](bold $style)'

[java]
symbol = ""
style = "fg:color1"
format = '[ $symbol ]($style)'

[nodejs]
symbol = ""
style = "fg:color1"
format = '[ $symbol ]($style)'



[python]
symbol = ' '
style = "fg:color10"
# This ensures it outputs nothing if virtualenv is empty
format = '[($symbol($virtualenv) )]($style)'
detect_extensions = []
detect_files = []
detect_folders = []



[rust]
symbol = ""
style = "fg:color1"
format = '[ $symbol ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color8"
format = '[$time ]($style)'

[os.symbols]
AlmaLinux = ""
Amazon = ""
Arch = ""
Debian = ""
Kali = ""
Linux = ""
Macos = ""
Manjaro = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Solus = "  "
SUSE = ""
Ubuntu = ""
Windows = "  "



# Matugen color mappings appended at the bottom
[palettes.colors]
# color1 = "#cebdfe"
color1 = "#5494f4"
color2  = "#cbc3dc"
color3  = "#211f24"
color4 = "#2b292f"
color5 = "#1d1b20"
color6    = "#141218"
color7   = "#db0ab8"
#color7   = "#e6e1e9"
color8 = "#0ce8a6"
#color8  = "#cbc3dc"
#color9   = "#ffb4ab"
color9   = "#4fff5b"
color10 = "#db1010"
