


@define-color surface rgba({{colors.surface.default.rgb}}, 0.65);
@define-color main-bg rgba({{colors.surface_container.default.rgb}}, 0.75);
@define-color notify-bg rgba({{colors.surface_container_low.default.rgb}}, 0.80);

.control-center {
    background: @main-bg;
    border-radius: 16px;
    border: 1px solid rgba({{colors.outline.default.rgb}}, 0.2);
    padding: 10px;
}

.notification {
    background: @notify-bg;
    border-radius: 12px;
    margin: 6px;
    border: 1px solid rgba({{colors.outline_variant.default.rgb}}, 0.15);
}
